### ISSUE TITLE
Checkout submodules recursively

### ISSUE THREAD

**Issue by docktermj** [Senzing/github-action-docker-buildx-build#7]
Change to

```yaml
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           fetch-depth: "0"
           submodules: recursive
```

See https://github.com/actions/checkout
